#+title: Inbox: su tiempo llegará

Jorge Luis Borges dijo: «Los lectores crean de nuevo los libros que leen. Shakespeare es hoy día más rico que cuando él escribía. Cervantes también. Cervantes fue enriquecido por Unamuno. Shakespeare fue enriquecido por Coleridge y Bradley. Así es como crece un escritor. Tras su muerte, continúa desarrollándose en la mente de sus lectores. Y la Biblia, por ejemplo, hoy día es más rica que cuando se escribieron sus diversas partes. Un libro se beneficia del paso del tiempo. Todo puede beneficiarlo. Incluso los malentendidos pueden ayudar a un autor. Todo ayuda, incluso la ignorancia o el descuido de los lectores. Después de haber leído un libro, se puede retener una impresión inexacta del mismo, pero esto significa que ha sido modificado en la memoria. A mí me sucede esto con frecuencia. ¡Caramba!, no sé si me atrevo a confesarlo, pero siempre que cito a Shakespeare, ¡me doy cuenta que lo he mejorado!».


Revisar el primer viaje a occidente de Guo Songtao.
