:PROPERTIES:
:ID: C0ADBA68-2416-4041-A4E8-E3F3778D9938
:ROAM_ALIASES: "topological space" "topology" "neighborhood" "topological spaces"
:END:
#+title: Topological spaces
#+SETUPFILE: ../../../setup.org

** Definition
Let \(X\) be a non-empty set and \(\tau\) a collection of subsets of \(X\) (i.e. \(\tau \subset \mathcal{P}(X)\)) such that: 1. \(X \in \tau\) 2. \(\emptyset \in \tau\) 3. If \(O_1, O_2, ...O_n \in \tau\), then \(O_1 \cap O_2 \cap ...\cap O_n \in \tau\) 4. If for each \(\alpha \in I\), \(O_\alpha \in \tau\), then \(\bigcup_{\alpha \in I}O_\alpha\in\tau\)

Then the set \((X, \tau)\) is called a /topological space/ and the set \(\tau\) itself is called a /topology over \(S\)/.
The sets \(A \in \tau\) are called the open sets of the space.
The set \(A\) such that its complement \(A^c\) is an open set (\(A^c\in \tau\)) are call close sets.

** Related concepts
*** Neighborhood
Given a topological space \((X, \tau)\), a subset \(N\) of \(X\) is called a /neighborhood/ of a point \(a \in X\) if \(N\) contains an open set that contains \(a\). Also, often times the concept of neighborhood is defined as just any open set containing \(a\).

*** Closure
Let \(A \subset X\), then we defined the /closure/ of \(A\) as
\[
Cl(A) = \overline{A} = \bigcap \left\{ C\text{ closed } : A\subset C\right\}
\]
i.e. \(\overline{A}\) is the smallest closed subset of \(X\) which contains \(A\).
For a point \(x\in X\) we have \(x \in \overline{A}\) iff, for each neighborhood \(N\) of \(x\), \(N \cap A \neq \emptyset\).

*** Interior
Again, let \(A \in X\), then the /interior/ of \(A\) is the set
\[
Int(A) = \mathring{A} = \bigcup \left\{U \text{ open } : U \subset A\right\}
\]
i.e. \(\mathring{A}\) is the largest open subset of \(X\) contained in \(A\).
A point \(x \in X\) is in the interior of \(A\) if \(A\) is a neighborhood of \(x\).

*** Boundary
Given a subset \(A\) of a topological space, a point \(x\) is said to be /in the boundary of \(A\)/ if \(x\) is in both the closure of \(A\) and the closure of the complement of \(A\).

*** Limit point
Given a subset A of a topological space, a point \(x\) is said to be /a limit point of \(A\)/ if every neighborhood of \(x\) contains at least one point of \(A\) other than \(x\) itself.

** Morphisms
In the [[id:6B755D9E-EB8E-4673-ADD0-B4411D410D52][category]] of topological spaces the arrows are the [[id:C9250EE3-0576-419B-923C-765C512516B2][continous maps]] between spaces.
