:PROPERTIES:
:ID: 9CEE2BBE-9DB7-4A0B-824C-512B3FEDF01B
:ROAM_ALIASES: "isomorphism" "isomorphisms" "automorphism"
:END:
#+title: Group Isomorphisms

*Definition* An /isomorphism/ \(\phi\) from a [[id:48FAF6F8-DD4A-49F5-89B1-DCE13AE4A2F7][group]] \(G\) to a group \(H\) is a one-to-one mapping from \(G\) onto \(H\) that preserver the group operation. That is
\[\phi(ab) = \phi(a)\phi(b) \quad\quad \text{for all a,b }\in G\]
If there exist an isomorphism from \(G\) onto \(H\), we say that \(G\) and \(H\) are /isomorphism/ and write \(G \cong H\).

By this definition every isomorphism is also an [[id:E5013D1E-0580-4393-B09A-B57053402595][homomorphism]]
​## Cayley's Theorem
Every group is isomorphic to a group of permutations.

** Properties of isomorphism Acting on Elements
Suppose that \(\phi\) is an isomorphism from a group \(G\) onto a group \(H\). Then 1. \(\phi(e_1)=e_2\) where \(e_1\), \(e_2\) are the identities of \(G\) and \(H\) respectively. 2. \(\phi(a^n) = [\phi(a)]^n\), for all \(n \in \mathbb{Z}\) and \(a \in G\). 3. \(ab = ba \iff \phi(a)\phi(b) = \phi(b)\phi(a)\), for all \(a, b \in G\). 4. \(G = \langle a\rangle\) iff \(H = \langle\phi(a)\rangle\). 5. \(|a| = |\phi(a)|\), for all \(a \in G\). 6. The equation \(x^k = b\) has the same number of solutions as \(x^k = \phi(b)\), for all fixed integer \(k\) and fixed element \(b\) of \(G\). 7. If \(G\) is finite, then \(G\) onto \(H\) have exactly the same number of elements of every order.

** Properties of Isomorphisms Acting on Groups
Suppose that \(\phi\) is an isomorphism from a group \(G\) onto a group \(H\). Then 1. \(\phi^{-1}\) is an isomorphism from \(H\) to \(G\). 2. \(G\) is Abelian iff \(H\) is Abelian. 3. \(G\) is cyclic iff \(H\) is cyclic. 4. If \(K\) is a subgroup of \(G\), then \(\phi(K) = \{\phi(k) | k \in K\}\) is a subgroup of \(H\).

** Automorphism
An isomorphism from a group \(G\) to itself is called an /automorphism/ of \(G\).

*** Inner Automorphism
Let \(G\) be a group, and let \(a \in G\). The function \(\phi_a\) defined by \(\phi_a(x) = axa^{-1}\) for all \(x \in G\) is called the /inner automorphism of \(G\) induced by \(a\)/.

*** \(Aut(G)\) and \(Inn(G)\) are Groups
The set \(Aut(G)\) of automorphism of the group \(G\) and the set \(Inn(G)\) of inner automorphism of a group are groups under the operation of function composition.

*** \(Aut(\mathbb{Z}_n) \cong U(n))\)
For every positive integer \(n\), \(Aut(\mathbb{Z}_n)\) is isomorphic to \(U(n)\).
