:PROPERTIES:
:ID: 58660F1E-EB64-4506-81E9-63FF79BD2E76
:ROAM_ALIASES: "manifold" "locally euclidean" "atlas" "chart" "smooth manifold" "smooth structure"
:END:
#+title: Manifolds
#+SETUPFILE: ../../../setup.org

** Locally Euclidean
A [[id:C0ADBA68-2416-4041-A4E8-E3F3778D9938][topological space]] \((X, \tau)\) is called *locally euclidean of dimension \(n\)* if:

For all \(x\in X\) there is an open set \(U \in \tau\) and a homeomorphism \(\varphi: U \to U'\) with \(U' \subseteq \mathbb{R}^n\) open.
The map \(\varphi: U\to U'\) is called a *chart* of \((X, \tau)\). More precisely, the tuple \((U, \varphi)\) forms a chart.

** Manifold
A manifold is a topological spacer \((M, \tau)\) that satisfies three properties: 1. \(M\) is a [[file:file:Hausdorff space.org][Hausdorff space]] 2. \(M\) is a [[Basis (topology).org][second-countable space]] 3. \(M\) is locally Euclidean of dimension \(n\)

A nonempty \(n\)-dimensional topological manifold cannot be homeomorphic to an \(m\)-dimensional manifold unless \(m=n\).

** Atlas
Two charts \((U, \varphi)\), \((V, \psi)\) are said to be *compatible* if either \(U \cap V = \emptyset\) or the transition map \(\psi \circ \varphi^{-1}: \varphi(U\cap V) \to \psi(U\cap V)\) is a diffeomorphism.

An *atlas* for a manifold \(M\) is a collection of charts whose domain cover \(M\). An atlas \(\mathscr{A}\) is called a *smooth atlas* if any two charts of \(\mathscr{A}\) are compatible with each other. A smooth atlas \(\mathscr{A}\) on \(M\) is *maximal* or *complete* if is not properly contained in any larger smooth atlas.

A *smooth structure* on \(M\) is a maximal smooth atlas, and a pair \((M, \mathscr{A})\) of a manifold together with a smooth structure is called a *smooth manifold*.
