#+title: Ajahn Bramali notes

[[https://www.youtube.com/playlist?list=PLf9HOK_Rf1M5ZR1dqXV61rIUEWMgCfFc8][Youtube series]]

* Mindfulness
Object oriented?

* Present awareness

* Breath meditation
Is important to wait until we get mindfulness and present awareness. Be in present, be **passive** and then the breath will come. Buddha's meditation does not direclty start with breath. Is important to not force anything.

Befriend your breath, make it a friend, comprehend it, feel compasion for it.

You can give rise to a sense of joy by being greateful, but without to much tought. A gentle nudge.


* Overcoming obstacles

There are five classic obstacles in the Buddhist theory of meditation. The best path to overcoming them starts at self-knowledge.

** The sensory world and thinking
- Is important to see that meditation helps with worldy problems and to value the practice.
- Gently remind that focusing on thoughts is not the way forward and slowly go back to the awareness state.

** Ill will
- This has to do with anger or irritation.
- This usually has to do with the past.
- The main way to overcome ill will is to forgive.

** Tiredness
- Relax, calm down the mind.
- After that, don't fight the tiredness, accept it.
- Think about joy.

** Restlessness and remorse
- Fir remorse: Leave with morality.
- For restlessness wait, and overcome the first two obstacles.
- Stay with the breath.

** Doubt
- Look at research.
- Trust the method.


* Other types of meditation

** Walking meditation
Look for a periodic path with a clear start and end point. Get into the repetition, allow yourself to focus on the feed. Like with breathing is important not to force the mind. Make everything come to you, in the most natural way possible.
