:PROPERTIES:
:ID:       0D19D1C2-D015-470E-BC35-5B4F1C6EFA5D
:END:
#+title: Confucio

* El punto de partida confuciano
Confucio resulta un personaje clave en cualquier intento de historiografía China debido al salto cualitativo que hace sobre el pensamiento chino. Es un personaje que marca la salida de la revolución filosófica que ocurre en su tiempo de manera paralela en tres mundo independientes: el griego, el hebreo y el indio.

A diferencia de las grandes figuras que marcan el cambio cultural en las otras civilizaciones, Confucio no es un pensador sistematico que cree un sistema filosófico, ni espiritual. El mismo consideraba su vida y obra un fracaso. Sin embargo, el mérito que es inegable es el de haber establecido el entramado ético que formo al hombre chino durante más de dos milenios.

Confucio aparece como la primera voz en primera persona en la historia del pensamiento chino, en este sentido es el primer autor chino. También es el primero en establecer unos principios éticos con carácter universal teniendo en cuenta a la humanidad de forma integra.


* El aprender, la calidad humana y el espíritu ritual

** Aprender
La visión confuciana del humano como ser capaz de la mejora lo lleva a tomar el aprendizaje como un punto de partida para su doctrina. Aprender se vuelve una acción deseable en sí misma, que debe hacerse por y para uno mismo. El aprendizaje siempre tiene una dimensión práctica, como es muy típico en el pensamiento chino el cómo se vuelve más importante que él qué.

*Primero el saber estar, esto permitene mantener el orden, luego las cuestiones teóricas vendrán de forma secundaria*.

Por tanto, aprender en confucio es aprender a ser humano (rén).


** El sentido de lo humano (rén)
Uno de los temas más imporantes en confucio es el de humanidad, en el sentido de la característica  de preocupación mutua. Un exégeta del siglo II define /rén/ como «la preocupación mutua que los hombres sienten debido al hecho de vivir juntos».

En Confucio, el /rén/ no supone un objetivo ideal que se debe alcanzar, sino, bien, un objetivo final al que tender, acercándose infinitamente. Muchas veces aparece la idea de la indulgencia, relacionada con la regla de oro de la moral, como base para comprender la naturaleza del /rén/. Se evita, pues, dar una definición concreta de este concepto, seguramente para evitar reduccionismos.

*** El Justo Medio
Aparece también en el camino hacia el /rén/ el concepto del /zhōngyōng/ ---muchas veces traducido, bajo una clara influencia aristotélica, por el Justo Medio---, que se coloca como «bien supremo» hacia el cual tiende toda la vida. Este equilibrio que se persigue debe de tener en cuenta el cambio y el intercambio, no es estático. Como el funambulista que trata de preservar su equilibrio con el movimiento.

*** Piedad filial
Como ocurría con la estructura religiosa en la antigüedad, la relación básica que define el concepto de /rén/ es la paterno-filial. Se entiende que es la primera relación de harmonía y reciprocidad que conocemos al llegar al mundo y se materaliza en el resto de formas de relacionarse. Es importante que el /rén/ es siempre una propiedad de segundo orden, entre las relaciones de humanos como miembros de la comunidad que habitan.

** La importancia del proceso ritual
La fórmula «Véncer su ego para volver a seguir los ritos» recuerda la importancia de la ascesis diri
gida a interiorizar ritualmente la humanidad de las relaciones de uno mismo con los demás. Para confucio el lǐ (espíritu ritual) es indisociable del /rén/. Estos conceptos ayudan a construir las necesidades éticas para alcanzar el orden y la harmonía.

* El hombre de bien
Confucio da al término /jūnzǐ/ ---que tradiconalmente significaba hidalgo, o hombre noble--- un sentido moral, el hombre de bien, que actúa rectamente. En este sentido, el /jūnzǐ/ será el hombre que sea capaz de incorporar los tres pilares de la ética confuziana, el aprendizaje, la humanidad y el espíritu ritual.

Todo este entramado ético no tiene solo el carácter indivual que parece a primera vistas, deber de extenderse a las relaciones supraindividuales. En la concepción china la familia se concibe como la extensión del individuo, y el Estado como una extensión de la familia; es, pues, el príncipe para sus súbditos lo que un padre para sus hijos. No hay división entre los saberes éticos y los políticos, ya que son siempre una extensión unos de otros.
