:PROPERTIES:
:ID: 41EA4065-F658-4538-8A60-26A7B07ACA33
:ROAM_ALIASES: "linear code"
:END:
#+title: Linear  code

A *linear code* of length \(n\) and dimension \(k\) is a [[id:C31DD475-75D9-4BB9-9DD5-536453386F9D][linear subspace]] \(C\) with dimension \(k\) of the [[id:C31DD475-75D9-4BB9-9DD5-536453386F9D][vector space]] \(\mathbb{F}^n_q\) where \(\mathbb{F}_q\) is the [[id:0A6751A9-127F-40CA-BD65-2F69B68F0DD8][finite field]] with \(q\) elements. In the most extended case where \(q = 2\) we call the code binary. The size of a code is the number of codewords and equals \(q^k\).

The *weight* of a codeword is the number of its elements that are non-zero.

The *distance* between two codewords is the Hamming distance between them. The Hamming distance between two equal-length strings of symbols is the number of positions at which the corresponding symbols are different.

The *distance* \(d\) of the linear code is the minimum weight of its nonzero codewords, or equivalently, the minimum distance between distinct codewords.

A linera code of length \(n\), dimension \(k\), and distance \(d\) is called an \([n, k, d]\) code.

** Generator and check matrices
As a linear subspace of \(\mathbb{F}^n_q\), the entire code \(C\) may be represented as the span of a set of \(k\) codewords. These basis codewords are often collated in the rows of a matrix \(G\) known as the *generator matrix* for the code \(C\). When \(G\) has the block matrix form \(\mathbf{G} = [I_k|P]\) where \(I_k\) denotes the \(k\times k\) identity matrix and \(P\) is some \(k\times (n -k)\) matrix, then we say \(G\) is in *standard form*.

A matrix \(H\) representing a linear function \(\phi: \mathbb{F}^n_q \to \mathbb{F}^{n-k}_q\) whose kernel is \(C\) is called a *check matrix*. Equivalently, \(H\) is a matrix whose null space is \(C\). If \(C\) is a code with a generating matrix in standard form, \(\mathbf{G} = [I_k|P]\), then \(\mathbf{H}=[-P^T|I_{n-k}\) is a check matrix for \(C\). The code generated by \(H\) is called the dual code of \(C\).

Linearity guarantees that the minimum Hamming distance \(d\) between a codeword \(c_0\) and any of the other codewords \(c \neq c_0\) is independent of \(c_0\). This follows from the property that the differences \(c - c_0\) is also a codeword, and the property that \(d(c, c_) = d(c-c_0, 0)\). This implies that
\[ 
\min_{c\in C, c\neq c_0} d(c, c_0)= \min_{c\in C, c\neq c_0} d(c-c_0, 0) = d
\]
In other words, in order to find out the minimum distance between the codewords of a linear code, one would only need to look at the non-zero codewords. The non-zero codeword with the smallest weight has then the minimum distance to the zero codeword, and hence determines the minimum distance of the code.

The distance \(d\) of a linera code \(C\) also equals the minimum number of linearly dependent columns of the check matrix \(H\).
