:PROPERTIES:
:ID: 32DD9FBC-97BE-4089-BA38-6C425F5D0AAF
:ROAM_ALIASES: "endomorphisms ring"
:END:
#+title: Endomorphism Ring

The [[id:E5013D1E-0580-4393-B09A-B57053402595][endomorphisms]] of an [[id:48FAF6F8-DD4A-49F5-89B1-DCE13AE4A2F7][abelian group]] \(X\) forms a [[id:3CC31C84-CF5C-4C2C-90A6-623847BFF49F][ring]]. This ring is called the *endomorphism ring* of \(X\), and denoted \(End(X)\), i.e. the set of all [[id:0A0A0964-760B-436D-B664-BD9B0C34CC42][homomorphism]] of \(X\) to itself. Addition of endomorphism aries naturally in a pointwise manner and multiplication via endomorphism composition.

In this way the endomorphisms of an abelian group forms a (unital) ring, with the zero map \(0: x \mapsto 0\) as additive identity and the identity map \(1: x \mapsto x\) as multiplicative identity.

** Description
Let \((A, +)\) be an Abelian Group, consider the set \(End(A)\) of group homomorphisms from \(A\) to \(A\).

Define addition as follows
given \(f, g \in End(A)\) define \(f + g: x \mapsto f(x) + g(x)\).
Under this operations \(End(A)\) is an Abelian Group.

With the additional operation of composition of homomorphisms, \(End(A)\) is a ring with multiplicative identity. This composition is explicitly \(fg : x \mapsto f(g(x))\). The multiplicative identity is the identity homomorphism on \(A\).
