#+title: Enūma Eliš

* Nombres del poema

Denominamos Poema babilónico de la Creación al largo poema épico escrito en acadio que generalmente se conoce como Enūma Eliš en el ámbito de los estudios orientales. La expresión acadia enúma eli$ significa literalmente «cuando en lo alto», y se trata de las dos primeras palabras del poema. Este es el título con el cual se le conocía ya en la antigiiedad entre los babilonios y los asirios. Aunque el título de /Poema babilónico de la Creación/ ha sido el que ha tenido más éxito en nuestros días, este título no describe exactamente el contenido esencial del poema, ya que la creación del universo y del hombre ocupa una proporción relativamente pequeña de la obra. De hecho, el poema debería titularse «La exaltación de Marduk», el dios nacional de Babilonia, ya que este es el tema principal de la composición.


* Tema

El poema comienza con la creación del mundo por parte de los dioses primordiales del mar. Pasando a contar el destrono de estos por su hijo Ea. A partir de ahí, la trama se centra en la guerra de venganza que comienza los dioses antiguos y como Marduk ---hijo de Ea y su Paladín escogido--- vence y crea el mundo con los restos del cadaver de la diosa primogénica Tiámat.


* Ascenso al trono de Marduk entre los dioses mesopotámicos

Marduk, dios de Babilonia, era un dios menor durante la hegemonía sumeria. Tras el comienzo de la supremacía babilónica, con el reinado de Hammurabi se le otorga entre los teólogos a Marduk la supremacía sobre las personas, pero sigue sin tener el trono entre dioses que luego pasará a tener.

Se cree que la composición de este poema ocurre tras la recuperación de la estatua de Marduk, robada por los ejércitos elamitas, por las tropas babilónicas. De esta forma, se entiende la entronazición de Marduk frente a los dioses como la proyección al mundo celestial del deseo de la ciudad de Babilonia por ganarse su momento de hegemonía en el mundo mesopotámico.

Durante la hegemonía sumeria el dios ejecutivo del panteón era Enlil, cuyo culto se organizaba alrededor de la ciudad santa de Nippur. Sin embargo, el En el Enūma Eliš no aparece nombrado Enlil hasta después de la victoria de los nuevos dioses. Y, a partir del reinado de Nabucodonosor I y durante todo el primer milenio, Marduk ocupará está posición de supremacía en el panteón mesopotámico. 


* Influencia de las cosmogonías babilónicas en el Génesis

Las principales teológicas ideas detrás del mito bíblico de la creación se pueden encontrar tanto en el Enūma Eliš como en otros mitos cosmogónicos babilónicos. Nabucodonosor II expulsó al pueblo de Israel de la región de Judea hacia el 590AC, lo que provocó que un número importante de sacerdotes judíos viviesen en Babilonia hasta el fin del edicto de expulsión proclamado por el rey Ciro de Persia.


* Creación de la humanidad

La creación de la humanidad supone uno de los momentos culminantes del poema. En este caso, el poema recoge con bastante fidelidad la tradición que ya era bien conocida desde la época paleobabilónica en Mesopotamia. Ea es la divinidad que se encarga de crear a los hombres bajo la supervisión de Marduk, y la materia prima para hacerlo es la sangre de Kingu, el amante de Tiámat, general de sus ejércitos y rival de Marduk. La humanidad es creada para liberar a los dioses de sus obligaciones cotidianas (VI 1-39). Este mitema tiene diversos precedentes, con algunas variantes, dentro de la literatura mesopotámica; el mito sumerio de Enki y Ninmah ya describe la manera en que estas dos divinidades crean la humanidad a partir del barro del Apsu. Las obligaciones que se atribuyen a la humanidad quedan bien concretadas en otros mitos, donde estos hombres y mujeres sustituirán a los dioses en sus tareas de abrir canales y mantenerlos en buen estado para la irrigación de los campos. Este es el caso del relato conocido como Atrabtasis o El Supersabio, escrito en acadio y que data del siglo XVI, donde se explica, entre otras cosas, la creación de la humanidad a partir de barro y la carne y la sangre de un dios.
